#! /usr/bin/perl

use strict;
use warnings;
use Date::Format;

# Read in commit message
my @msg = <>;

### Tweak it
#
my $utime = $ENV{GIT_AUTHOR_DATE};
my $author = $ENV{GIT_AUTHOR_EMAIL};
# Handy environment variables documented in git-filter-branch(1)

$utime =~ s/ [-+]\d{4}//; # brutally lose timezone
my @lt = localtime($utime);
my $date = strftime("%Y-%m-%d", @lt);
$msg[0] = "[$date $author] ".$msg[0];

# Print it out
print @msg;
